# Generated by Django 5.2.17 on 2026-09-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='mode',
            field=models.CharField(choices=[('assistant', 'Assistant'), ('tutor', 'Tutor')], default='assistant', max_length=12),
        ),
    ]
