# Generated by Django 5.2.17 on 2026-09-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_notebook_conversation_notebook_document_notebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usageevent',
            name='kind',
            field=models.CharField(choices=[('chat', 'Chat'), ('api', 'Api'), ('voice', 'Voice'), ('tool', 'Tool'), ('study', 'Study')], max_length=20),
        ),
    ]
